name: Regression Tests

on:
  push:
    branches: [ master ]

jobs:
  api_tests:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        cd getgeeks/project/
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run API Tests
      run: |
        cd getgeeks/project/backend/
        chmod +x ./run.sh
        ./run.sh
    - name: Upload api test results
      uses: actions/upload-artifact@v3.0.0
      if: always()
      with:
        name: api-reports
        path: getgeeks/project/backend/logs
    - name: Test Reporter
      uses: dorny/test-reporter@v1.5.0
      with:
        name: API Test Result
        path: getgeeks/project/backend/logs/xunit.xml
        reporter: java-junit

  web_tests:
    needs: api_tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        cd getgeeks/project/
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Web Tests
      run: |
        cd getgeeks/project/frontend/
        chmod +x ./run.sh
        ./run.sh
    - name: Upload api test results
      uses: actions/upload-artifact@v3.0.0
      if: always()
      with:
        name: web-reports
        path: getgeeks/project/frontend/logs
    - name: Test Reporter
      uses: dorny/test-reporter@v1.5.0
      with:
        name: Web Test Result
        path: getgeeks/project/frontend/logs/xunit.xml
        reporter: java-junit